import localFont from "next/font/local";
import "./globals.css";
import RainbowAndWagmiProvider from "@/RainbowAndWagmiProvider";
import Layout from "./components/shared/Layout";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RainbowAndWagmiProvider>
          <Layout>{children}</Layout>
        </RainbowAndWagmiProvider>
        <Toaster />
      </body>
    </html>
  );
}
